version: '3.8'

services:
  televid-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: televid-bot
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - .env
